version: "3.1"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./env/backend.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
