version: "3.1"

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
